### ISSUE TITLE
feat: 테스트 코드 작성

### ISSUE THREAD

**Issue by yoownny** [yoownny/java-racingcar-7#5]
## Description
테스트 코드를 생성하여 다양한 경우의 테스트를 진행한다.

## Todo
- [x] 공동 우승자가 있는 경우
- [x] 아무도 전진하지 않는 경우
- [x] 자동차 이름이 비어있는 경우
- [x] 시도 횟수가 문자인 경우
- [x] 시도 횟수가 음수인 경우
